package:
  name: {% set name = "jsonpointer" %}{{ name }}
  version: {% set version = "2.0" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c192ba86648e05fdae4f08a17ec25180a9aef5008d973407b581798a83975362

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonpointer

about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Identify specific nodes in a JSON document (RFC 6901)'
  dev_url: https://github.com/stefankoegl/python-json-pointer
  doc_url: https://python-json-pointer.readthedocs.io
