package:
  name: {% set name = "jsonpath-ng" %}{{ name|lower }}
  version: {% set version = "1.4.3" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1fc75b877e9b2f46845a455fbdcfb0f0d9c727c45c19a745d02db620a9ef0be

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
  entry_points:
    - jsonpath.py = jsonpath_ng.bin.jsonpath:entry_point
requirements:
  build:
    - pip
    - python
  run:
    - decorator
    - ply
    - python
    - six

test:
  imports:
    - jsonpath_ng

about:
  home: https://github.com/h2non/jsonpath-ng
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/apache-2.0.txt
  summary: Finally, a JSONPath implementation for Python that aims to be standard compliant. That's all. Enjoy it.
