package:
  name: {% set name = "chromedriver" %}{{ name }}
  version: {% set version = "2.45" %}{{ version }}

source:
  url: https://{{ name }}.storage.googleapis.com/{{ version }}/{{ name }}_linux64.zip  # [linux]
  sha256: d4a5eec0a3b7fec9bcb71353233dde38630e51b29fa7b218cdd196e2e4487da7  # [linux]

  url: https://{{ name }}.storage.googleapis.com/{{ version }}/{{ name }}_mac64.zip  # [osx]
  sha256: aa0f416a48e20185da62525869c1f98f994bf99f241d6ce2eb1af6ceb517c425  # [osx]

  url: https://{{ name }}.storage.googleapis.com/{{ version }}/{{ name }}_win32.zip  # [win]
  sha256: 8f3373a260a524410e25ea643ecb0175ed49a078088c7ab4d88db323ee19a230  # [win]

build:
  number: 0
  script:
    - mv {{ name }} $PREFIX/bin/  # [unix]
    - move {{ name }}.exe %SCRIPTS%\  # [win]

requirements:
  host: []
  run: []

test:
  commands:
    - chromedriver --version
    - chromedriver --help

about:
  home: http://chromedriver.chromium.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ['RECIPE_DIR'] }}/BSD-3-Clause.txt
  summary: >
    ChromeDriver is a standalone server which implements WebDriver's wire
    protocol for Chromium.
