jobs:
- template: ci/job.robotlab.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.robotlab.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

- template: ci/job.robotlab.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

variables:
  MINICONDA_VERSION: 4.5.4
  CONDA_VERSION: 4.5.11

trigger: [master]

pr: [master]
