jobs:
- template: ci/job.robotlab.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    condaPlatform: linux-64

- template: ci/job.robotlab.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13
    condaPlatform: osx-64

- template: ci/job.robotlab.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    condaPlatform: win-64

variables:
  MINICONDA_VERSION: 4.5.4
  CONDA_VERSION: 4.5.11

trigger: [master]

pr: [master]
