{% set name = "robotframework" %}
{% set version = "3.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
    sha256: 7e29b2ac415e6bdbde348d25c0c759c6d3df012c897b31dcf98fd2dd94cee7bd
    folder: dist
  - url: https://github.com/robotframework/robotframework/archive/v{{ version }}.tar.gz
    sha256: f1e15c027ebe60d5d770a28fbd7a931323e95ce7b07a52a87a62637c80056065
    folder: src

build:
  number: 0
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - robot = robot.run:run_cli
    - rebot = robot.rebot:rebot_cli

requirements:
  build:
    - patch
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - docutils
    - enum34  # [py<35]
    - lxml
    - pillow
    - pygments
    - pyyaml
  source_files:
    - src/utest
    - src/atest
    - src/README.rst
  imports:
    - robot
    - robot.api
    - robot.conf
    - robot.htmldata
    - robot.libdocpkg
    - robot.libraries
    - robot.model
    - robot.output
    - robot.output.console
    - robot.parsing
    - robot.reporting
    - robot.result
    - robot.running
    - robot.running.arguments
    - robot.running.timeouts
    - robot.utils
    - robot.variables
    - robot.writer
  commands:
    - robot --version
    - rebot --version

about:
  home: http://robotframework.org
  license: Apache-2.0
  license_file: dist/LICENSE.txt
  summary: Generic automation framework for acceptance testing and RPA
  doc_url: http://robotframework.org/robotframework/{{ version }}/RobotFrameworkUserGuide.html
  dev_url: https://github.com/robotframework/robotframework
  description: >
    Robot Framework is a generic open source automation framework for acceptance
    testing, acceptance test driven development (ATDD), and robotic process
    automation (RPA). It has simple plain text syntax and it can be extended
    easily with libraries implemented using Python or Java.

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
    - alexvds
    - bollwyvl
