{% set extensions = "@jupyterlab/toc@0.6.0 @jupyter-widgets/jupyterlab-manager@0.38.1 jupyterlab_robotmode@1.1.0" %}
{% set lab_min = "0.35.4" %}
{% set lab_max = "0.36" %}

package:
  name: {% set name = "robotlab" %}{{ name }}
  version: {% set version = "0.10.0" %}{{ version }}

source:
  - path: ../../robotlab
    folder: robotlab
  - url: https://github.com/robots-from-jupyter/robotkernel/archive/{{ version }}.tar.gz
    sha256: 0b62946fcc291ccc0c37ccd27dbc361ea0b09d0abe8c3c46eea358c1487ea5ed
    folder: robotkernel

build:
  number: 2
  entry_points:
    - robotlab = robotlab.labapp:main
    - robotlab-extension = robotlab.labextensionapp:main
    - robotlab-examples = robotlab.examples:copy_robotkernel_examples
  script:
    - cd robotlab
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
    - {{ PYTHON }} -m robotlab.scripts
    - {{ PYTHON }} -m robotlab.labextensionapp install {{ extensions }} --no-build
    - {{ PYTHON }} -m robotlab.labextensionapp list
    - {{ PYTHON }} -m robotlab.labapp build
    - rm -rf {{ PREFIX }}/share/jupyter/robotlab/staging  # [unix]
    - rd /s /q {{ PREFIX }}\\share\\jupyter\\robotlab\\staging  # [win]
    - {{ PYTHON }} -m robotlab.labextensionapp list
    - cd {{ SRC_DIR }}
    - cd robotkernel
    - cd examples
    - mkdir -p {{ PREFIX }}/var/www/robotkernel-examples  # [unix]
    - cp *.ipynb {{ PREFIX }}/var/www/robotkernel-examples  # [unix]
    - md {{ PREFIX }}\var\www\robotkernel-examples  # [win]
    - copy *.ipynb {{ PREFIX }}\var\www\robotkernel-examples  # [win]

requirements:
  host:
    - jupyterlab >={{ lab_min }},<{{ lab_max }}
    - nodejs >=8,<9
    - pip
    - python
    - pyshortcuts
  run:
    - ipywidgets
    - jupyterlab >={{ lab_min }},<{{ lab_max }}
    - nodejs >=8,<9
    - python
    - robotkernel >={{ version }}

test:
  imports:
    - robotlab
    - robotlab.examples
    - robotlab.icons
    - robotlab.labextensionapp
    - robotlab.scripts
    - robotlab.shortcuts
  commands:
    - robotlab --version
    - robotlab-extension list
    - robotlab-examples

about:
  home: https://github.com/robots-from-jupyter/robotlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: robotlab/LICENSE
  summary: A JupyterLab built for a robotkernel
