{% set robot = "3.1.2" %}
{% set robot_conda = ">=4.7.12,<4.8" %}
{% set robot_fox = ">=68.0.2,<69" %}
{% set robot_jupyterlab = "==1.2.4" %}
{% set robot_node = ">=11,<12" %}
{% set robot_pywinpty = ">=0.5.5" %}
{% set robot_starters = ">=0.2.2a0,<0.3.0a0" %}
{% set robot_widgets = ">=7.5.1" %}
{% set robotkernel = "1.3.0" %}

package:
  name: {% set name = "robotlab" %}{{ name }}
  version: {% set version = "2020.01.0" %}{{ version }}

source:
  - path: ../../robotlab
    folder: robotlab
  - url: https://github.com/robots-from-jupyter/robotkernel/archive/{{ robotkernel }}.tar.gz
    sha256: e3c384621f37c9471ca0c65c44c8203c7a99207cbb155a70c7b9063f2b9832e8
    folder: robotkernel
  # we do the jupyterlab build off-line to keep conda-build time low
  - path: ../../_artifacts/app_dir
    folder: app_dir

build:
  number: 0
  entry_points:
    - robotlab = robotlab.labapp:main
    - robotlab-extension = robotlab.labextensionapp:main
    - robotlab-shortcuts = robotlab.shortcuts:make_shortcuts
    - robotlab-examples = robotlab.examples:copy_robotkernel_examples
    - robotlab-tutorial = robotlab.tutorial:copy_robotkernel_tutorial
  script:
    - {{ PYTHON }} {{ RECIPE_DIR }}/builder.py  # [unix]
    - {{ PYTHON }} {{ RECIPE_DIR }}\builder.py  # [win]
    - cd robotlab
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - pip
    - python
  run:
    - conda {{ robot_conda }}
    - firefox {{ robot_fox }}
    - geckodriver
    - ipywidgets {{ robot_widgets }}
    - jupyter-starters {{ robot_starters }}
    - jupyterlab {{ robot_jupyterlab }}
    - jupytext >=1.3.1
    - matplotlib-base >=3.1.2
    - nodejs {{ robot_node }}
    - py-opencv
    - pyshortcuts
    - python
    - pywinpty {{ robot_pywinpty }}  # [win]
    - restinstance
    - rise >=5.6.0
    - robotframework =={{ robot }}
    - robotframework-jupyterlibrary
    - robotframework-seleniumscreenshots
    - robotframework-seleniumtestability
    - robotframework-whitelibrary  # [win]
    - robotkernel =={{ robotkernel }}

test:
  imports:
    - robotlab
    - robotlab.examples
    - robotlab.labextensionapp
    - robotlab.launch
    - robotlab.paths
    - robotlab.shortcuts
    - robotlab.tutorial
  commands:
    - robotlab --version
    - robotlab-extension list
    - robotlab-tutorial
    - robotlab-examples
    - cd robotkernel-examples
    - jupyter nbconvert --execute --ExecutePreprocessor.timeout=600 OpenCV.ipynb  # [not osx]
    - cd ..
    - mkdir Desktop  # [unix]
    - HOME=$(pwd) robotlab-shortcuts  # [unix]

about:
  home: https://github.com/robots-from-jupyter/robotlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: robotlab/LICENSE
  summary: A JupyterLab built for robotkernel as part of the RobotLab distribution
