package:
  name: '{% set name = "robotframework-jupyterlibrary" %}{{ name }}'
  version: '{% set version = "0.2.0" %}{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63bb7bd94bb21fbd6f88a640b605d51728bc48a1a9aebbe27ee033c218a5aa03
  patches:
    - 001-lab-114-icons.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python
  run:
    - pillow
    - python
    - robotframework >=3.1
    - robotframework-seleniumlibrary >=4.1.0,<5
    - six

test:
  imports:
    - JupyterLibrary

about:
  home: https://robotframework-jupyterlibrary.rtfd.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for automating (testing of) Jupyter end-user applications and extensions
  dev_url: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary
