{% set name = "pyshortcuts" %}
{% set version = "1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 505307516626a9be1e9a23565e53564fcf11374e13a677bfcec94a255be0c4e1

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - pyshortcut = pyshortcuts:shortcut_cli

requirements:
  host:
    - pip
    - python
  run:
    - six
    - python
    - pywin32  # [win]

test:
  requires:
    - wxpython
  imports:
    - pyshortcuts
    - pyshortcuts.darwin
    - pyshortcuts.linux
    - pyshortcuts.windows
    - pyshortcuts.wxgui

  commands:
    - pyshortcut --help


about:
  home: https://github.com/newville/pyshortcuts
  license: MIT
  license_file: LICENSE
  summary: create desktop shortcuts to python scripts on Windows, Mac, or Linux
