{% set name = "jupyter_starters" %}
{% set version = "0.2.2a0" %}

package:
  name: {{ name | replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8773e03f8e05532197aa16f4a634bb3d1f8fe858658a7f20bf64879fd78e367f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - notebook >=5.3

test:
  requires:
    - pytest-asyncio
    - pytest-cov
    - python <3.8.0a0  # [win]
  imports:
    - jupyter_starters
  commands:
    - pytest --pyargs jupyter_starters --cov jupyter_starters

about:
  home: https://github.com/deathbeds/jupyterlab-starters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Parameterized file and directory starters for JupyterLab.'
