package:
  name: {% set name = "robotkernel" %}{{ name }}
  version: {% set version = "0.10.2" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93560cb763d5efe3785e920aa59b2f2f2048ea84bda9f4a6868340143a9f4028

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
  entry_points:
    - nbrobot = robotkernel.nbreader:robot
    - nblibdoc = robotkernel.nbreader:libdoc

requirements:
  build:
    - patch
  host:
    - pip
    - python
  run:
    - docutils
    - ipykernel
    - lunr
    - nbformat
    - pillow
    - pygments
    - python
    - robotframework >=3.1

test:
  imports:
    - robotkernel
  commands:
    - jupyter kernelspec list

about:
  home: https://github.com/robots-from-jupyter/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework IPython kernel for Jupyter Notebook and JupyterLab
