package:
  name: {% set name = "robotkernel" %}{{ name }}
  version: {% set version = "1.0rc1" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7914dbb25efb70b2392f6864c554b057936826f8341868d6ece88f3bc3094e27

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
  entry_points:
    - nbrobot = robotkernel.nbreader:robot
    - nblibdoc = robotkernel.nbreader:libdoc

requirements:
  host:
    - pip
    - python
  run:
    - docutils
    - ipykernel
    - lunr
    - nbformat
    - pillow
    - pygments
    - python
    - robotframework >=3.1

test:
  imports:
    - robotkernel
  commands:
    - jupyter kernelspec list

about:
  home: https://github.com/robots-from-jupyter/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework IPython kernel for Jupyter Notebook and JupyterLab
