package:
  name: '{% set name = "robotkernel" %}{{ name }}'
  version: '{% set version = "1.3.0" %}{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8401e9bee8df473e586a1607c2b50c628dd01493ac258569f56720e345360019

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - nbrobot = robotkernel.nbreader:robot
    - nblibdoc = robotkernel.nbreader:libdoc

requirements:
  host:
    - pip
    - python
  run:
    - docutils
    - ipykernel
    - lunr
    - nbformat
    - pillow
    - pygments
    - python
    - robotframework >=3.1

test:
  imports:
    - robotkernel
  commands:
    - jupyter kernelspec list

about:
  home: https://github.com/robots-from-jupyter/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework IPython kernel for Jupyter Notebook and JupyterLab
