{% set name = "robotframework-seleniumscreenshots" %}
{% set version = "0.9.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 400f3c2213578d1e249216170cd1dd1e86999492d9e731a030beca0d87181b17

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - pip
    - python
  run:
    - python
    - robotframework >=3.0.2
    - robotframework-SeleniumLibrary>=3.2.0

test:
  imports:
    - SeleniumScreenshots

about:
  home: https://github.com/datakurre/robotframework-seleniumscreenshots
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Robot Framework keyword library for capturing annotated screenshots with SeleniumLibrary
  doc_url: https://datakurre.github.io/robotframework-seleniumscreenshots
