package:
  name: {% set name = "rfc3987" %}{{ name|lower }}
  version: {% set version = "1.3.8" %}{{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3c4d257a560d544e9826b38bc81db676890c79ab9d7ac92b39c7a253d5ca733

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - pip
    - python
  run:
    - python
    - regex

test:
  imports:
    - rfc3987

about:
  home: https://pypi.org/project/rfc3987/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING.txt
  summary: Parsing and validation of URIs (RFC 3896) and IRIs (RFC 3987) 
  dev_url: https://github.com/dgerber/rfc3987
