parameters:
  name: Linux
  vmImage: ubuntu-16.04
  condaSubdir: linux-64

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - ${{ if eq(parameters.name, 'MacOSX') }}:
        - script: |
            HOMEBREW_NO_AUTO_UPDATE=1 \
            brew tap caskroom/cask \
            && brew cask install google-chrome \
            && brew cask install firefox
          displayName: Install Browsers

      - template: steps.conda.yml

      - template: steps.common.yml
        parameters:
          name: ${{ parameters.name }}
          condaSubdir: ${{ condaSubdir }}
